name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          template: classic
          base: header
          config_timezone: Europe/Warsaw
          
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 10
          plugin_activity_load: 300
          plugin_activity_visibility: all
          
          plugin_starlists: yes
          plugin_starlists_languages: yes
          plugin_starlists_limit: 10
          plugin_starlists_limit_languages: 5
          plugin_starlists_limit_repositories: 3

